const fs = require('fs');
if (fs.existsSync('config.env')) require('dotenv').config({ path: './config.env' });

module.exports = {
  "SESSION_ID": process.env.SESSION_ID || "eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQ0hMWUJJOE5oemNOMXZEVElPR0ZrNlpZNFg2WWVVTFJXNHhuakUzWGJFcz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoibFdxbDRRT3kxQStoN0dPRUcyelNzTG1nNVpReFZ6eTdOZk15cytxdjFTOD0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJvTktULzVuTCswYUlDWGMvazk5ZVFBbFpHMitONFJkMWZPZW43S1NZdmtjPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJZb2lhY0FXWDQrK1EzTnFkR3VNR2I5T1ZwQ3RUY3ZrSnN6enpHUGx3ZUhVPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlFDVTBpM25pbml2Yng3RWVxUWltczlad2pINlZwRnl6dnBpdDJ2MkpPMVE9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjFaQkxnekorWHNTejhtdUtWWnBmV1FhSTMvS0FvMmE3aEpNUnJON3lvbWs9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiNkNkWkh5S21OTlVoS0hGQ1BHRHdHM2xUTTZ6b2JVY3ZNRzl2L2tCUFAzYz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoidkRXcHdnenRkWXVpRERJOTBJT0NSN0l1ZTR1UjVmc1Nud20wczFEcmtGVT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InRXQ1NPd3BuSyswcEtkc2d0Z1l2a3FESzh2RjZpNURLZlBtWE04THIrZVNyNXdqdjFyR0x4RTdZVTQxRnVKOGtYdnRqUGszM3llUjNlTEdmR3RObmd3PT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTIwLCJhZHZTZWNyZXRLZXkiOiJIMVBwTzJ4c3ZtcUszajVRaVl4M1E5ZWFjQ0xPUWpFUDlERC9NbEUwanAwPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwicmVnaXN0ZXJlZCI6dHJ1ZSwicGFpcmluZ0NvZGUiOiI3REcxWUtDOCIsIm1lIjp7ImlkIjoiOTE5MDY0NTYwODQwOjNAcy53aGF0c2FwcC5uZXQiLCJuYW1lIjoiQWthc2giLCJsaWQiOiI3MDI1MzE5OTUwMzM3ODozQGxpZCJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDTC92eE1rRkVMalk2OUFHR0FJZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiMXlDcmM5UHBiZklxTVlselNGcW1ZTGl6ckZmUDJWUVF3RjMzYS85ZjFrcz0iLCJhY2NvdW50U2lnbmF0dXJlIjoiclB6b05zdkpPNk1OZ2E5bWdYSHZsZDViaW9rZEVwODg4VVVnanViVDRSVFp6UFBXTlp6VkNiRHc0STltbUZnZWJlWTJMK0FaWHQ2SnJNNkMxUDA4QXc9PSIsImRldmljZVNpZ25hdHVyZSI6Imd6Vkk3ZktlZW1hZ0REMm4wdXFhNlVwMDBaUy95eUdJaGpvbDV3ektYd1JwcjFhUCtxRUc1N3dKc05xdVMwRXY3d2tJTHczdmNPMUF2dUp4U05pSmlBPT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiOTE5MDY0NTYwODQwOjNAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCZGNncTNQVDZXM3lLakdKYzBoYXBtQzRzNnhYejlsVUVNQmQ5MnYvWDlaTCJ9fV0sInBsYXRmb3JtIjoic21iYSIsInJvdXRpbmdJbmZvIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQ0FnSURRZ0MifSwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzgwMTQ5MzE2LCJteUFwcFN0YXRlS2V5SWQiOiJBQUFBQU1JOCJ9",
  "ALIVE_IMG": process.env.ALIVE_IMG || "https://raw.githubusercontent.com/HyHamza/HyHamza/refs/heads/main/Images/logo.jpg",
  "PREFIX": process.env.PREFIX || ".",
  "AUTO_READ_STATUS": process.env.AUTO_READ_STATUS === 'true',
  "MODE": process.env.MODE || "public",
  "OWNER_NUMBER": process.env.OWNER_NUMBER || "919064560840",
  "OWNER_NAME": process.env.OWNER_NAME || "AKASH",
  "ALWAYS_ONLINE": process.env.ALWAYS_ONLINE === 'false',
  "PRESENCE": process.env.PRESENCE || "null",
  "OMDB_API_KEY": process.env.OMDB_API_KEY || "76cb7f39",
  "READ_CMD": process.env.READ_CMD === 'true',
  "AUTO_VOICE": process.env.AUTO_VOICE === 'false',
  "AUTO_STICKER": process.env.AUTO_STICKER === 'false',
  "AUTO_REPLY": process.env.AUTO_REPLY === 'false',
  "AUTO_REACT": process.env.AUTO_REACT === 'false',
  "WELCOME": process.env.WELCOME === 'true',
  "ANTI_BAD": process.env.ANTI_BAD === 'true',
  "ANTI_LINK": process.env.ANTI_LINK === 'true',
  "ANTI_GROUP_LINK": process.env.ANTI_GROUP_LINK === 'true',
  "ANTI_DELETE": process.env.ANTI_DELETE === 'true',
  "ANTI_VIEW_ONCE": process.env.ANTI_VIEW_ONCE === 'true',
  "ANTI_BOT": process.env.ANTI_BOT === 'true',
  "PREMIUM_USERS": process.env.PREMIUM_USERS || "919064560840",
  "COUNTRY_BLOCK": process.env.COUNTRY_BLOCK === 'false',
  "COUNTRY_BLOCK_CODE": process.env.COUNTRY_BLOCK_CODE || "972",
  "EMOJI": process.env.EMOJI || "🙄",
  "AUTO_TYPING": process.env.AUTO_TYPING === 'false'
};
